value_a=float(input("Digite o valor do lado A: "))
value_b=float(input("Digite o valor do lado B: "))
value_c=float(input("Digite o valor da lado C: "))
if value_a+value_b>value_c and value_a+value_c>value_b and value_b+value_c>value_a : print("Esse valores formam um triangulo")
else: print("Esse valores nao formam um tringulo")
if value_a==value_b and value_a==value_c and value_b==value_c: print("Esse triangulo e equilatero")
elif value_a==value_b or value_a==value_c or value_c==value_b: print("Esse triangulo isoceles")
else: print("Esse triangulo e escaleno")