print("Vamos calcular seu imc")
peso=float(input("Digite seu Peso, em kg: "))
altura=float(input("Digite sua altura, em metros: "))
imc=peso/(altura*altura)
if imc<18.5:print("abaixo do peso")
elif imc<25:print("peso ideal")
elif imc<30:print("Sobrepeso")
elif imc<40:print("Obesidade")
else:print("Obesidade morbida")